version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    groups:
      docker:
        patterns:
          - "*"  # Group all Docker updates into a single larger pull request
    schedule:
      interval: weekly
